"""Constantes compartidas de EduPass."""

ESTADO_ACTIVO = "activo"
ESTADO_INACTIVO = "inactivo"

ESTADO_ALUMNO_ACTIVO = ESTADO_ACTIVO
ESTADO_ALUMNO_INACTIVO = ESTADO_INACTIVO
ESTADOS_ALUMNO_VALIDOS = frozenset(
    {
        ESTADO_ALUMNO_ACTIVO,
        ESTADO_ALUMNO_INACTIVO,
    }
)

ROL_ADMINISTRADOR = "administrador"
ROL_ESCANER = "escaner"
ROLES_AUTENTICACION = (ROL_ADMINISTRADOR, ROL_ESCANER)

QR_ESTADO_ACTIVO = "activo"
QR_ESTADO_UTILIZADO = "utilizado"
QR_ESTADO_INVALIDADO = "invalidado"

QR_VIGENCIA_SEGUNDOS = 30
QR_TOKEN_BYTES = 32
QR_TOKEN_LONGITUD = 43
QR_TOKEN_PATRON = r"^[A-Za-z0-9_-]{43}$"

TIPO_MOVIMIENTO_ENTRADA = "entrada"
TIPO_MOVIMIENTO_SALIDA = "salida"
TIPOS_MOVIMIENTO = frozenset(
    {
        TIPO_MOVIMIENTO_ENTRADA,
        TIPO_MOVIMIENTO_SALIDA,
    }
)

PUNTO_PLANTEL_ACCESO_PRINCIPAL = "acceso_principal"
PUNTOS_PLANTEL_MOVIMIENTO = frozenset(
    {
        PUNTO_PLANTEL_ACCESO_PRINCIPAL,
    }
)
PUNTO_PLANTEL_LONGITUD_MAXIMA = 64
